apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: maximo20/fastapi-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: HNG_LESSON_DAY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.api.configmap.name }}
                  key: HNG_LESSON_DAY
            - name: HNG_API_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.api.configmap.name }}
                  key: HNG_API_ORIGINS
            - name: HNG_API_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.api.configmap.name }}
                  key: HNG_API_PORT
            - name: HNG_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.api.configmap.name }}
                  key: HNG_API_HOST
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.secret.name }}
                  key: api-key
