apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: NodePort
  selector:
    app: fe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: maximo20/react-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.fe.configmap.name }}
                  key: REACT_APP_API_URL
            - name: REACT_APP_LESSON_DAY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.fe.configmap.name }}
                  key: REACT_APP_LESSON_DAY
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fe.secret.name }}
                  key: api-key
