apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  HNG_LESSON_DAY: day1
  HNG_API_ORIGINS: http://localhost:3000
  HNG_API_PORT: "8000"
  HNG_API_HOST: "0.0.0.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  api-key: ""
