apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-configmap
data:
  REACT_APP_API_URL: http://api-service:8000 
  REACT_APP_LESSON_DAY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: fe-secret
type: Opaque
data:
  api-key: ""
